apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: eventhub-sink-connector
  labels:
    strimzi.io/cluster: eventhub-kafka-connect
spec:
  class: org.apache.camel.kafkaconnector.azureeventhubs.CamelAzureeventhubsSourceConnector
  tasksMax: 2
  config:
    camel.source.path.namespace: ens-jmc-ping
    camel.source.path.eventHubName: ens-jmc-ping-receiver
    camel.source.endpoint.connectionString: "${file:/opt/kafka/external-configuration/eventhubping/eventhubpingsecret:eventhubspassword}"
