apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: eventhub-kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: ens-jmc-kafka.servicebus.windows.net:9093
  config:
    group.id: eventhub-kafka-connect
    offset.storage.topic: eventhub-kafka-connect-offsets
    config.storage.topic: eventhub-kafka-connect-configs
    status.storage.topic: eventhub-kafka-connect-status
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: eventhubping
        secret:
          secretName: eventhubpingsecret
  # image: acrjmcsri7x.azurecr.io/strimzi-custom-connect:latest
  authentication:
    type: plain
    username: $ConnectionString
    passwordSecret:
      secretName: eventhubkafkasecret
      password: eventhubspassword
  tls:
    trustedCertificates: []
  template:
    pod:
      imagePullSecrets:
        - name: acr
