apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: azure-kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: ens-jmc-company-a.servicebus.windows.net:9093
  config:
    group.id: azure-kafka-connect
    offset.storage.topic: azure-kafka-connect-offsets
    config.storage.topic: azure-kafka-connect-configs
    status.storage.topic: azure-kafka-connect-status
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: cosmoscompanyb
        secret:
          secretName: cosmoscompanybsecret
  image: acrjmcsri7x.azurecr.io/strimzi-custom-connect:latest
  authentication:
    type: plain
    username: $ConnectionString
    passwordSecret:
      secretName: eventhubcompanyasecret
      password: eventhubspassword
  tls:
    trustedCertificates: []
  template:
    pod:
      imagePullSecrets:
        - name: acr
